### ISSUE TITLE
Usar títulos estándar y/o significativos para los capítulos

### ISSUE THREAD

**Issue by JJ** [AlexMenor/heroes#29]
Planteamiento quizás debería explicar que se trata de la implementación. Backend, si es parte de la implementación, ¿no iría en ese capítulo? Recuerda la jerarquía conceptual de la memoria, y también la "narrativa". Primero planteas, luego implementas, luego despliegas...

**Comment by AlexMenor** [comment]
En un principio empecé a estructurarlo así. El problema es que el capítulo de implementación quedaría larguísimo y habría demasiado profundidad en mi opinión (subsubsubsecciones).

**Comment by JJ** [comment]
No es tanto problema, siempre que cada nivel sea homogéneo y coherente.

**Comment by AlexMenor** [comment]
El esquema actual es:

1. Introducción: Problema, análisis, estado del arte, qué vamos a hacer...
2. Planteamiento: Solución a alto nivel y metodología agnóstica de donde corra el código.
3. Backend: Detalles de implementación del microservicio
4. Frontend: Detalles de implementación de la aplicación.

La alternativa entiendo que sería:

1. Introducción.
2. Planteamiento: Metodología solo.
3. Implementación: Solución a alto nivel y todos los detalles de implementación.

**Comment by JJ** [comment]
@AlexMenor Correcto.
