### ISSUE TITLE
Aclara las decisiones técnicas tomadas en cada paso

### ISSUE THREAD

**Issue by JJ** [AlexMenor/heroes#34]
Aparte de lo dicho en #31, tienes que hablar también de las decisiones de arquitectura tomadas; dices como un hecho que usas un método cliente servidor, pero hay muchas otras opciones, como serverless o basado en contenedores y cosas por el estilo.

**Comment by AlexMenor** [comment]
Las únicas serían cliente-servidor o p2p, no? 

Las otras opciones que comentas creo que son de despliegue, pero de eso no he hablado en la documentación.

**Comment by JJ** [comment]
No necesariamente. Microservicios, basada en mensajería, streaming... Hay muchas posibilidades. Serverless no sólo es de despliegue, lo que hace es que no necesitas diseñar nada de la infraestructura y los datos estarían en un SaaS. Sería una especie de microservicio, aunque dependerá de cuantos servicios tengas.

**Comment by AlexMenor** [comment]
Te había entendido mal, te refieres a que tengo un monolito? Creo que ya explico bastante en ese sentido: Implemento un solo microservicio para esta iniciativa y hablo del escalado horizontal. Puedes ponerme un ejemplo de lo que no queda claro?

**Comment by JJ** [comment]
No, en general es que siempre tienes que explicar qué decisión tomas en el contexto de las decisiones posibles, y por qué lo has hecho. No es algo específico en este caso, sino más general.
