### ISSUE TITLE
HU: Como usuario, después de dar mi consentimiento, mi localización debe emitirse para que el sistema pueda avisarme si alguien cercano necesita ayuda

### ISSUE THREAD

**Issue by AlexMenor** [AlexMenor/heroes#6]
- [x] Buscar sistema de persistencia adecuado.
- [x] Interfaz adecuada con el front end.
- [x] Front end
- [ ] Tests

**Comment by JJ** [comment]
No puedes cerrar los issues sin los tests correspondientes. En este caso, además, deberías tener tests end to end.

**Comment by AlexMenor** [comment]
Estoy de acuerdo
